### ISSUE TITLE
UpDown controls' "Value" property causes errors.

### ISSUE THREAD

**Issue by IvanStoychev** [xceedsoftware/wpftoolkit#1549] opened 2019-11-09 21:45 UTC
WPF project on .Net Core 3.0 with Visual Studio 2019 version 16.3.6.

When using the following namespace:
`xmlns:xtended="http://schemas.xceed.com/wpf/xaml/toolkit"`
and using any of the UpDown controls in it like so:
`<xtended:IntegerUpDown Value="3" Name="myUpDownControl"/>`

The following error is shown:

Severity | Code | Description
---- | ---- | ----
Error | XDG0062 | Could not load type 'System.Int32?' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

The "type" referenced in the error description changes for the different UpDown controls, accordingly (so, for example, for a "DecimalUpDown" the type is "System.Decimal?").

The problems only appears when using/setting the "Value" attribute/property/whatever. Oddly enough one project on one Windows 10 machine refused to draw the UpDown control, at all. On another Windows 7 machine the project started and the control was drawn but using the up or down arrows caused Visual Studio to crash, while the WPF debug app showed no problems. Restarting Visual Studio after that, without changing a thing, still shows the error but now starting in debug and using the arrows causes no problems.

**Comment by CriticalFlaw** [comment] 2020-03-12 16:53
I'm seeing the same error with the IntegerUpDown control in my .NET Core 3.1 WPF app. Hoping this will be fixed with the release of v4.0 where .NET Core 3 will be officially supported (https://github.com/xceedsoftware/wpftoolkit/issues/1428)

![image](https://user-images.githubusercontent.com/6818236/76545456-2e9e8480-6460-11ea-8f24-42c5af721306.png)

**Comment by XceedBoucherS** [comment] 2020-10-15 16:28
Hi,
Try installing the latest version of Visual Studio. It looks like its fixed.
I had the problem in v16.3.6. I installed v16.7.6 and problem is gone.
Thank you.

**Closed by XceedBoucherS** 2020-10-15 16:28 UTC

**Comment by ianmichaelbrown** [comment] 2021-06-22 08:36
I am using VS2019 v16.9.4 and this problem still exists.  My toolkit version is 4.1.0 and my project is .NET Core 3.1.  The issue exists for all the 'UpDown' controls I'm using (so maybe a base class issue), though my code actually does work despite the designer errors.  GitHub does say that support for .NET Core 3+ is not in the free toolkit, but I really feel that it should be.  It's totally fine to have extra controls in the paid-for versions, but I think If you're going to provide a control in the free version it should work in all cases.  Incidentally, can anyone confirm that this issue does NOT exist in the non-free toolkit versions (when targeting .NET Core)?  If so, are there any plans to make it work in the free version?
Many thanks.

**Comment by XceedBoucherS** [comment] 2021-06-22 11:21
Hi,
I can not reproduce errors in XAML or Design Mode for UpDown controls. 
I define an IntegerUpDown and I use VS 2019 v16.9.2 in a.NET Core3.1 app under Windows10.
![image](https://user-images.githubusercontent.com/29377763/122915356-acbb2d80-d329-11eb-9cea-b37729fced34.png)

I remember an issue like that for UpDown controls and I think yes, it was related to a generic templated base class. But this error shouldn't prevent the application from starting. It must be related to Visual Studio XAML parser.

The free and Plus version of the Toolkit should react in the same way regarding to this issue. 
As for having .NET Core working in the free version, we are evaluating this.

Thank you

**Comment by ianmichaelbrown** [comment] 2021-06-23 09:27
Hi again and thanks for your reply.  However, I have just created my own clean solution and still see the same problem.  This is a new .NET Core 3.1 WPF app, using toolkit version 4.1.0.

My initial design, with no errors, is shown here:
![image](https://user-images.githubusercontent.com/62079103/123071423-8d490100-d40c-11eb-99ef-78344ae9d355.png)

However as soon as I add the Value property, an error is raised:
![image](https://user-images.githubusercontent.com/62079103/123071645-c1242680-d40c-11eb-868d-21a8372a1a44.png)

The same happens if I only add FormatString (with or without a string):
![image](https://user-images.githubusercontent.com/62079103/123071802-e022b880-d40c-11eb-8a46-635177ebd134.png)

FYI, in my real project I am also using ByteUpDown and TimeSpanUpdown, which both display the same issue.
I don't know if this is (at least partly) a Visual Studio problem, but I thought you would upload this example in case it helps.  If you would like more information, please just ask.  

Thanks,
Ian.

**Comment by XceedBoucherS** [comment] 2021-06-25 13:07
Hi,

What I can see for now is that a .NET Core 3.1 project can use a System.Int32 from assembly System.Runtime v4.2.2.0 while Xceed.Wpf.Toolkit.NETCore.dll can use a System.Int32 from assembly System.Runtime v4.2.1.0.
You can try to modify your project so it targets .NET Core 3 and see if the warning remains.
The Toolkit is build for .NETCore3 and up, so a base System.Runtime is used.

**Comment by lawatunnel** [comment] 2022-06-07 19:44
A simple restart of Visual Studio did it for me...
Even with System.Runtime version 4.1.2
I am using VS2022 v17.1.2

**Comment by lawatunnel** [comment] 2022-06-07 20:11
Hey guys,

**Restarting Visual Studio fixes it for me...**
I have changed App.config to target System.Runtime 4.2.1 
and it's still acting like this when adding or changing XAML code.
(I'm using VS2022 Community v17.1.2, my project targets .NET Framework 4.6.2)
