### ISSUE TITLE
TimePicker input issue

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#1134] opened 2017-07-13 13:00 UTC
<b>itabaev[CodePlex]</b> <br />There is a problem when entering minutes into TimePicker.
TimePicker allows you to enter only the first digit of the minute.
The second digit can only be entered if you enter the same digit twice.
An example in gif.
The order of input: 1, 2, 3, 4, 5, 6, 1, 1, 2.

**Comment by xceedsoftware** [comment] 2017-07-13 13:00
<b>BoucherS[CodePlex]</b> <br />Hi, 

This should be fixed in v3.1. 

――――
Get more controls, features, updates and technical support with 
Xceed Toolkit Plus for WPF

**Comment by Omcsesz** [comment] 2021-03-30 18:47
Is it fixed yet?

**Comment by XceedBoucherS** [comment] 2021-04-06 11:38
Hi, can you reproduce this in the LiveExplorer of the ClickOnce app (https://xceed.com/en/our-products/product/toolkit-plus-for-wpf) ?
If yes, can you submit a sample showing the issue please ?
Thank you

**Comment by Omcsesz** [comment] 2021-04-12 12:55
> 
> 
> Hi, can you reproduce this in the LiveExplorer of the ClickOnce app (https://xceed.com/en/our-products/product/toolkit-plus-for-wpf) ?
> If yes, can you submit a sample showing the issue please ?
> Thank you

Sorry, I have no access to the Plus version, I can not verify that.

**Comment by XceedBoucherS** [comment] 2021-04-12 20:10
The LiveExplorer is free to use. 
You also have it in the sources available here on github. Just run the code and start the LiveExplorer and see if this is an issue in the LiveExplorer. This should already be fixed.

**Comment by Omcsesz** [comment] 2021-04-17 21:49
I tried, and it seems to be working.
I think we can close this!

**Closed** 2021-04-19 13:40 UTC
Labels: CodePlex
